# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P2_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 659)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_sumar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sumar.setGeometry(QtCore.QRect(260, 180, 411, 101))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_sumar.setFont(font)
        self.btn_sumar.setStyleSheet("background-color: cyan;\n"
"border: 4px solid red;\n"
"border-radius:20px;\n"
"color: black;")
        self.btn_sumar.setObjectName("btn_sumar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 81))
        self.label.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label.setObjectName("label")
        self.txt_resultado = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_resultado.setGeometry(QtCore.QRect(380, 350, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.txt_resultado.setFont(font)
        self.txt_resultado.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_resultado.setText("")
        self.txt_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_resultado.setObjectName("txt_resultado")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 10, 271, 81))
        self.label_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 360, 271, 81))
        self.label_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.txt_A = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_A.setGeometry(QtCore.QRect(320, 20, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.txt_A.setFont(font)
        self.txt_A.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_A.setText("")
        self.txt_A.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_A.setObjectName("txt_A")
        self.txt_B = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_B.setGeometry(QtCore.QRect(770, 20, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.txt_B.setFont(font)
        self.txt_B.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_B.setText("")
        self.txt_B.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_B.setObjectName("txt_B")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sumar.setText(_translate("MainWindow", "SUMAR"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">A:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">B:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">Suma:</span></p></body></html>"))
